Repository SQLStreamStore/SQLStreamStore, pull requests merged in 2018-11, with the labels that each got.

#214 Just use one ms-sql container instance reducing system resource usage.
  src/SqlStreamStore.MsSql.Tests/MsSqlStreamStoreFixture.cs
  src/SqlStreamStore.MsSql.V3.Tests/MsSqlStreamStoreV3Fixture.cs
Labels: infra

#215 Remove GetStreamMessageCount from StreamStoreBase
  src/SqlStreamStore.MsSql.V3.Tests/MsSqlStreamStoreV3AcceptanceTests.cs
  src/SqlStreamStore.MsSql/MsSqlStreamStore.cs
  src/SqlStreamStore.MsSql/MsSqlStreamStoreV3.cs
  src/SqlStreamStore.MsSql/ScriptsV3/GetStreamMessageBeforeCreatedCount.sql
  src/SqlStreamStore.MsSql/ScriptsV3/Scripts.cs
  src/SqlStreamStore.Postgres.Tests/PostgresStreamStoreAcceptanceTests.cs
  src/SqlStreamStore.Postgres/PgSqlScripts/ReadStreamMessageBeforeCreatedCount.sql
  src/SqlStreamStore.Postgres/PgSqlScripts/Scripts.cs
  src/SqlStreamStore.Postgres/PostgresStreamStore.cs
  src/SqlStreamStore/InMemory/InMemoryStreamStore.cs
  src/SqlStreamStore/Infrastructure/StreamStoreBase.cs
Labels: enhancement

#216 In tests, ensure databases have compatibility level set to 110 (SqlServer 2012)
  src/SqlStreamStore.MsSql.Tests/MsSqlStreamStoreFixture.cs
  src/SqlStreamStore.MsSql.V3.Tests/MsSqlStreamStoreV3Fixture.cs
Labels: infra, store:ms-sql

#220 reformat build scripts to have an option per line
  build.cmd
  build.sh
Labels: infra
